version: '3.8'

services:
  alteryx-converter:
    build: .
    container_name: alteryx-pyspark-converter
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - APP_ENV=production
    volumes:
      - ./uploads:/app/uploads  # Persist uploaded files
      - ./logs:/app/logs        # Persist logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s